# Generated by Django 2.2.17 on 2021-04-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=12)),
                ('viber', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Dane kontaktowe',
                'verbose_name_plural': 'Dane kontaktowe',
            },
        ),
        migrations.AlterModelOptions(
            name='pricelist',
            options={'ordering': ['name'], 'verbose_name': 'Cennik', 'verbose_name_plural': 'Cennik'},
        ),
    ]
