# Generated by Django 2.2.17 on 2021-04-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210415_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='NIP',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='contact',
            name='REGON',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='contact',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='street',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
